-- 🤖 Generated by Gemini
-- User-to-user like interactions.

CREATE TABLE likes (
    like_id VARCHAR(36) PRIMARY KEY,
    from_user_id VARCHAR(36) NOT NULL,
    to_user_id VARCHAR(36) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(from_user_id, to_user_id)
);

-- Records of users spending bolts to unlock received profiles.
CREATE TABLE like_unlocks (
    user_id VARCHAR(36) NOT NULL,
    like_id VARCHAR(36) NOT NULL,
    unlocked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, like_id)
);
