-- 🤖 Generated by Gemini
-- Real-time user location and sharing status.

CREATE TABLE locations (
    user_id VARCHAR(36) PRIMARY KEY,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    share_location BOOLEAN DEFAULT TRUE,
    location_name TEXT,
    geohash VARCHAR(12),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
