-- 🤖 Generated by Gemini
-- Offline meeting events and participants.

CREATE TABLE meetings (
    meeting_id VARCHAR(36) PRIMARY KEY,
    author_id VARCHAR(36) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    category VARCHAR(50) NOT NULL,
    category_emoji VARCHAR(10),
    gender VARCHAR(10),
    location_name TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    meeting_date DATE,
    meeting_time TIME,
    status VARCHAR(20) DEFAULT 'OPEN',
    keywords TEXT, -- JSON array of strings
    views INTEGER DEFAULT 0,
    max_participants INTEGER DEFAULT 10,
    current_participants INTEGER DEFAULT 1,
    participants TEXT, -- JSON array of user IDs
    images TEXT, -- JSON array of image URLs
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
