-- 🤖 Generated by Gemini
-- User account and credential metadata.

CREATE TABLE users (
    user_id VARCHAR(36) PRIMARY KEY,
    nickname VARCHAR(50) NOT NULL,
    provider VARCHAR(20) DEFAULT 'email',
    provider_user_id VARCHAR(100),
    email VARCHAR(255),
    password_hash TEXT,
    volt_balance INTEGER DEFAULT 100,
    warning_count INTEGER DEFAULT 0,
    status VARCHAR(20) DEFAULT 'active',
    suspended_until TIMESTAMP,
    free_chat_remaining INTEGER DEFAULT 3,
    verified_name VARCHAR(100),
    verified_phone_number VARCHAR(20),
    verified_birth_date VARCHAR(10),
    verified_identity_key TEXT,
    verified_identity_provider VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
