-- 🤖 Generated by Gemini
-- Volt currency wallets and transaction history.

CREATE TABLE bolt_wallets (
    user_id VARCHAR(36) PRIMARY KEY,
    balance INTEGER DEFAULT 100,
    last_login_reward_at TIMESTAMP,
    profile_complete_bonus_claimed BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bolt_ledger (
    entry_id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL,
    amount INTEGER NOT NULL, -- Positive for earn, negative for spend
    reason VARCHAR(100) NOT NULL,
    balance_after INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
