-- 🤖 Generated by Gemini
-- Chat rooms, messages, and read status.

CREATE TABLE chat_rooms (
    chat_room_id VARCHAR(36) PRIMARY KEY,
    room_type VARCHAR(20) DEFAULT '1v1',
    member_ids TEXT NOT NULL, -- JSON array of user IDs
    meeting_id VARCHAR(36),
    last_message TEXT,
    last_message_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chat_messages (
    message_id VARCHAR(36) PRIMARY KEY,
    chat_room_id VARCHAR(36) NOT NULL,
    sender_id VARCHAR(36) NOT NULL,
    message_type VARCHAR(20) DEFAULT 'TEXT',
    content TEXT,
    image_url TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chat_reads (
    chat_room_id VARCHAR(36) NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    last_read_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (chat_room_id, user_id)
);
