-- 🤖 Generated by Gemini
-- Real-time user presence for lightning matching.

CREATE TABLE lightning_presences (
    user_id VARCHAR(36) PRIMARY KEY,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    display_latitude DOUBLE PRECISION,
    display_longitude DOUBLE PRECISION,
    is_online BOOLEAN DEFAULT TRUE,
    last_seen_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
