-- 🤖 Generated by Gemini
-- Successful user matches resulting from mutual likes.

CREATE TABLE matches (
    match_id VARCHAR(36) PRIMARY KEY,
    user_a VARCHAR(36) NOT NULL,
    user_b VARCHAR(36) NOT NULL,
    chat_room_id VARCHAR(36) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_a, user_b)
);
