-- 🤖 Generated by Gemini
-- Detailed user profile information for matching.

CREATE TABLE profiles (
    profile_id VARCHAR(36) PRIMARY KEY, -- Maps to user_id
    nickname VARCHAR(50) NOT NULL,
    age INTEGER NOT NULL,
    gender VARCHAR(10),
    job VARCHAR(100),
    mbti VARCHAR(4),
    keywords TEXT, -- JSON array of strings
    height INTEGER,
    body_type VARCHAR(50),
    drinking VARCHAR(50),
    religion VARCHAR(50),
    dating_style VARCHAR(100),
    ideal_type VARCHAR(100),
    profile_images TEXT, -- JSON array of URLs/paths
    status_message TEXT,
    profile_completion INTEGER DEFAULT 50
);
