-- 🤖 Generated by Gemini - API/DB Alignment
-- This table persists metadata for images uploaded during onboarding and chat.

CREATE TABLE uploads (
    upload_id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL,
    file_path TEXT NOT NULL,
    file_type VARCHAR(20) NOT NULL, -- 'profile_image' or 'chat_image'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
